# Carregando os dados

```{r}
x = c(24, 13, 7, 5, 3, 2)
barplot(x)
```

# Cores no R

```{r}
?colors
colors()  # lista de nomes das cores
```

```{r}
browseURL("https://datalab.cc/rcolors")
```

# Usando cores

```{r}
barplot(x, col = "red3")  # vermelho
barplot(x, col = "gray30")  # cinza
```

```{r}
barplot(x, col = rgb(.80, 0, 0))      # vermelho
barplot(x, col = rgb(.30, .30, .30))  # cinza
```

```{r}
barplot(x, col = rgb(205, 0, 0, max = 255))     # vermelho
barplot(x, col = rgb(77, 77, 77, max = 255)) # cinza
```

RGB hexcodes
```{r}
barplot(x, col = "#CD0000")  # vermelho
barplot(x, col = "#4D4D4D")  # cinza
```

Usando os índices
```{r}
barplot(x, col = colors() [555])  # vermelho
barplot(x, col = colors() [183])  # cinza
```

# Multiplas cores

```{r}
barplot(x, col = c("red3", "gray30"))
barplot(x, col = c("#4D4D4D", "#CD0000"))
```

# Paletas de cores

```{r}
?palette
palette()
```

```{r}
barplot(x, col = 1:6)
```

```{r}
barplot(x, col = rainbow(6))
```

```{r}
barplot(x, col = heat.colors(6))
```

```{r}
barplot(x, col = terrain.colors(6))
```

```{r}
barplot(x, col = topo.colors(6))
```

```{r}
barplot(x, col = cm.colors(6))
```

# Limpeza

```{r}
rm(list = ls()) 
dev.off()
cat("\014")
```

Limpeza feita 😊
